### ISSUE TITLE
node-pre-gyp WARN Using needle for node-pre-gyp https download？

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [geocompass/MapPT#1]
[图片]
按照操作npm i 安装依赖后，启动项目报错
请问你们node版本事多少

**Comment by Liquid-Zhangliquan** [comment]
![image](https://user-images.githubusercontent.com/23397455/68849435-09e20c80-070d-11ea-886c-133ec66dfebc.png)

**Comment by LOUSANPANG** [comment]
> [图片]
> 按照操作npm i安装依赖后，启动项目报错请问
> 你们节点版本事多少

删除依赖重新`npm i`，中途不要中断。尝试一下。
